const MenuConfig = [
    {
        title:'instruct',
        key:'/instruct'
    },
    {
        title:'degree',
        key:'/degree'
    },
    {
        title:'coerness',
        key:'/coreness'
    },
    {
        title:'distance',
        key:'/distance'
    },
    {
        title:'cluster',
        key:'/cluster'
    },
    {
        title:'attack',
        key:'/attack'
    },
    {
        title:'subgraph_size',
        key:'/subgraph_size'
    },
    {
        title:'submap_counts',
        key:'/submap'
    }
]
export default MenuConfig;